spring:
  application:
    name: microservice
  main:
    banner-mode: off

management:
  tracing:
    sampling:
      probability: 1.0F

  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.zalando.logbook: trace